---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/nanorobocop/http-test-server.git
    branch: master

- name: docker-image
  type: docker-image
  source:
    repository: registry.mansur.moscow/http-test-server
    username: {{registry_username}}
    password: {{registry_password}}

jobs:
- name: job-test
  plan:
  - get: repo
    trigger: true
  - task: task-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.11-alpine
      inputs:
      - name: repo
      params:
        CGO_ENABLED: "0"
      run:
        path: go
        args:
        - test
        - ./...
        - -v
- name: job-vet
  plan:
  - get: repo
    trigger: true
  - task: task-vet
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.11-alpine
      inputs:
      - name: repo
      params:
        CGO_ENABLED: "0"
      run:
        path: go
        args:
        - vet
        - -v
        - ./...
- name: job-build
  serial: true
  plan:
  - get: repo
    passed:
    - job-vet
    - job-test
    trigger: true
  - put: docker-image
    params:
      build: repo 
